export interface IResearch {
    sp: number
    esp: number
    su: number
    mb: number
    ih: number
    sk: number
    tk: number
    tt: number
    io: number
    vt: number
    mu: number
    eb: number
    ld: number
    nt: number
    pf: number
    he: number
    sf: number
    el: number
    bt: number
    st: number
    ht: number
    rf: number
    ns: number
    am: number
    te: number
    nuk: number
    ion: number
    hyp: number
    gty: number
    kv: number
}
